import {
  getCourseById,
  getCoursesByCategoryId,
  createCourse,
  updateCourse,
  deleteCourseCascade,
  getLecturesByCourseId,
  createLecture,
  
  updateLecture,
  deleteLecture,
  getMaterialsByLectureId,
  createMaterialService,
  updateMaterial as updateMaterialService,
  deleteMaterial as deleteMaterialService,
} from "../services/course.service.js";

import fs from "fs/promises";
import { uploadToS3, getSignedUrlFromKey } from "../utils/s3Service.js";

/* =========================
   COURSE
========================= */

// GET /courses/:courseId
export const getCourse = async (req, res, next) => {
  try {
    const course = await getCourseById(req.params.courseId);

    if (!course) {
      return res.status(404).json({ message: "Course not found" });
    }

    res.json({ success: true, data: course });
  } catch (err) {
    next(err);
  }
};

// GET /categories/:categoryId
export const getCoursesByCategory = async (req, res, next) => {
  try {
    const courses = await getCoursesByCategoryId(req.params.categoryId);
    console.log("courses:", courses);
    
    res.json({
      success: true,
      count: courses.length,
      data: courses,
    });
  } catch (err) {
    next(err);
  }
};

// POST /courses (ADMIN)
export const createCourseHandler = async (req, res, next) => {
  try {
    const course = await createCourse({
      ...req.body,
      createdBy: req.user.userId,
      status: "DRAFT",
    });

    res.status(201).json({ success: true, data: course });
  } catch (err) {
    next(err);
  }
};

// PUT /courses/:courseId (ADMIN)
export const updateCourseHandler = async (req, res, next) => {
  try {
    const updated = await updateCourse(req.params.courseId, req.body);
    res.json({ success: true, data: updated });
  } catch (err) {
    next(err);
  }
};

// DELETE /courses/:courseId (ADMIN)
export const deleteCourseHandler = async (req, res, next) => {
  try {
    await deleteCourseCascade(req.params.courseId);
    res.json({
      success: true,
      message: "Course and all related content deleted",
    });
  } catch (err) {
    next(err);
  }
};

/* =========================
   LECTURES
========================= */

// GET /courses/:courseId/lectures
export const getLectures = async (req, res, next) => {
  try {
    const lectures = await getLecturesByCourseId(req.params.courseId);
    res.json({ success: true, data: lectures });
  } catch (err) {
    next(err);
  }
};

// POST /courses/:courseId/lectures (ADMIN)
export const createLectureHandler = async (req, res, next) => {
  try {
    const lecture = await createLecture({
      courseId: req.params.courseId,
      ...req.body,
    });

    res.status(201).json({ success: true, data: lecture });
  } catch (err) {
    next(err);
  }
};

// PUT /courses/:courseId/lectures/:lectureId (ADMIN)
export const updateLectureHandler = async (req, res, next) => {
  try {
    const updated = await updateLecture(
      req.params.courseId,
      req.params.lectureId,
      req.body
    );

    res.json({ success: true, data: updated });
  } catch (err) {
    next(err);
  }
};

// DELETE /courses/:courseId/lectures/:lectureId (ADMIN)
export const deleteLectureHandler = async (req, res, next) => {
  try {
    await deleteLecture(req.params.courseId, req.params.lectureId);
    res.json({ success: true, message: "Lecture deleted" });
  } catch (err) {
    next(err);
  }
};

/* =========================
   MATERIALS
========================= */

// GET /courses/:courseId/lectures/:lectureId/materials
export const getMaterials = async (req, res, next) => {
  try {
    const materials = await getMaterialsByLectureId({
      courseId: req.params.courseId,
      lectureId: req.params.lectureId,
    });
    
    const materialsWithUrls = await Promise.all(
      materials.map(async (material) => {
        const downloadUrl = await getSignedUrlFromKey(
          material.s3Key,
          300 // 5 minutes
        );

        return {
          ...material,
          downloadUrl,
        };
      })
    );

    res.json({
      success: true,
      data: materialsWithUrls,
    });
  } catch (err) {
    next(err);
  }
};


// POST /courses/:courseId/lectures/:lectureId/materials (ADMIN)
export const createMaterialHandler = async (req, res, next) => {
  try {
    if (!req.file) {
      return res.status(400).json({
        success: false,
        message: "File is required",
      });
    }

    const { courseId, lectureId } = req.params;
    const { title } = req.body;

    // materialId / materialOrder are generated by attachMaterialMeta
    const materialId = req.materialId;
    // const materialOrder = await getNextMaterialOrder({
    //   courseId,
    //   lectureId,
    // });

    // 1 Upload to S3 (Option 1: stable, machine-only key)
    const { s3Key, size, mimeType  } = await uploadToS3({
      file: req.file,
      courseId,
      lectureId,
      materialId,
    });

    // 2️ Remove local temp file (best effort)
    await fs.unlink(req.file.path).catch(() => {});

    // 3️ Persist metadata via service (human-facing info lives in DB)
    const material = await createMaterialService({
      courseId,
      lectureId,
      body: {
        title,
      },
      file: {
        displayName:req.body.displayName??req.file.originalname,
        mimetype: req.file.mimetype
      },
      meta: {
        materialId,
        s3Key,
        size,
        mimeType
      },
    });

    res.status(201).json({
      success: true,
      data: material,
    });
  } catch (err) {
    // Cleanup local file if something failed before unlink
    if (req.file?.path) {
      await fs.unlink(req.file.path).catch(() => {});
    }
    next(err);
  }
};


// PUT /courses/:courseId/lectures/:lectureId/materials/:materialId (ADMIN)
export const updateMaterialHandler = async (req, res, next) => {
  try {
    const updated = await updateMaterialService({
      courseId: req.params.courseId,
      lectureId: req.params.lectureId,
      materialId: req.params.materialId,
      body: req.body,
      file: req.file,
    });

    res.json({ success: true, data: updated });
  } catch (err) {
    next(err);
  }
};

// DELETE /courses/:courseId/lectures/:lectureId/materials/:materialId (ADMIN)
export const deleteMaterialHandler = async (req, res, next) => {
  try {
    await deleteMaterialService({
      courseId: req.params.courseId,
      lectureId: req.params.lectureId,
      materialId: req.params.materialId,
    });

    res.json({ success: true, message: "Material deleted" });
  } catch (err) {
    next(err);
  }
};
